### ISSUE TITLE
What is the difference between arm-64v7 and v7a? Can i download on v8a?

### ISSUE THREAD

**Issue by ScottN13** [zgfg/ToyBox-Ext#1]

**Comment by zgfg** [comment]
See in the README, module uses the official prebuilt ToyBox binaries from Landley site:
http://landley.net/toybox/bin

If you unzip the module installation file, you will see that three ToyBox binaries from the Landley are included:
toybox-aarch64
toybox-armv7m
toybox-armv7l

At the time of installation, module tests them one by one, in that order,
takes the first of the three that works on your platform and renames it and saves to:
/data/adb/modules/ToyBox-Ext/toybox-ext

E.g., if you have ARM v8, toybox-aarch64 should work for you and module will use that one for toybox-ext binary

If toybox-aarch64 does not work for you, module will test and install toybox-armv7m (or toybox-armv7l) as toybox-ext for your phone

---

If you don't believe :), you can test yourself, download the binaries from Landley, save them to eg:
/data/local/tmp

Mark them executable by:
chmod 755 /data/local/tmp/toybox-*

and test which of those Landley prebuilt binaries execute on your phone.
Use Terminal emulator and test eg:
/data/local/tmp/toybox-aarch64 --help

Eg, toybox-i486, toybox-mips64 and so will not work on ARM phones.
toybox-armv4l will work but that is for some ancient ARM devices (and I did not include into the module)

For ARM v7 and v8, only the above three make sense (all three will work) and the module installs the most appropriate one for your platform

You can check the file size and eg MD5 checksum between the installed toybox-ext and your downloaded ones, to see which one the module chose and installed

---

Btw, on the Landley ToyBox page:
https://landley.net/toybox

you can find the ToyBox source code and building instructions and build/compile the binary yourself and test on your phone

Eventually, you can replace the toybox-ext binary with another one, you must save it to the same place, make sure it is chmod 755, and reboot the phone

**Comment by zgfg** [comment]
.
